default:
  tags: [ nixFlakes ]

stages:
  - build

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

flake check:
  stage: build
  script: nix flake check
