workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
  - nix-ci

nix-ci:
  stage: nix-ci
  image: nixpkgs/nix-flakes:latest
  interruptible: true
  script:
    - nix flake check
    - nix build .#nixosConfigurations.ipsmin.config.system.build.toplevel
    - nix build .#nixosConfigurations.nelvte.config.system.build.toplevel
