workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "flake-update"'

stages:
  - periodic
  - nix-ci

include:
  - local: .gitlab-ci/flake-update.yml
    rules:
      - if: '$CI_COMMIT_BRANCH == "flake-update"'
  - local: .gitlab-ci/nix-ci.yml
    rules:
      - if: '$CI_MERGE_REQUEST_IID'
      - if: '$CI_COMMIT_TAG'
      - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
