repos:
  # Some generic hooks that should be universally useful
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Format nix code nicely
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.2.0
    hooks:
      - id: nixpkgs-fmt
