keys: &all
  - &matrss age1d84zfp3p9r2jg9fxfp0kf557ct36ppc7s7e3zwnuc00uy4q90uqsqwh3cy
  - &hazuno age168pargwepjcvtq87h0p8cct8jtmx04aer5c73zq4mfl0qf63le5s39c3pd
  - &ipsmin age1a2v5p3u4tlad6v4d4jd3h9hcwxkz0up5jye4nh5u6xvrznml9dcqxpc8x0
  - &mpanra age1n4tp8q0flwz222ecnwuhlj5nmqcn3v5q738gyep8f43c4yuqlgaswjrpf4
  - &nelvte age15rc2xk90qs50n5msp970kpme90u4kjjvh9z34v7n94hax5myjpfqs5ymxe
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *matrss
        - *ipsmin
        - *nelvte
  - path_regex: secrets/terraform/[^/]+\.yaml$
    key_groups:
      - age:
        - *matrss
  - path_regex: secrets/hazuno/[^/]+\.yaml$
    key_groups:
      - age:
        - *matrss
        - *hazuno
  - path_regex: secrets/ipsmin/[^/]+\.yaml$
    key_groups:
      - age:
        - *matrss
        - *ipsmin
  - path_regex: secrets/mpanra/[^/]+\.yaml$
    key_groups:
      - age:
        - *matrss
        - *mpanra
  - path_regex: secrets/nelvte/[^/]+\.yaml$
    key_groups:
      - age:
        - *matrss
        - *nelvte
