nix-ci:
  stage: nix-ci
  image: nixpkgs/nix-flakes:latest
  before_script:
    - |-
      if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
        cat >> /etc/nix/nix.conf << EOF
        substituters = ssh://nix-ssh@ara.matrss.de https://cache.nixos.org
        trusted-public-keys = ara.matrss.de-1:ZQzhLCE7akrXB8TvU7Nts3tn7oDujt/GMXQPo5gGYsU= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
        require-sigs = true
      EOF
        eval $(ssh-agent -s)
        echo "$NIX_CACHE_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        cat .known-hosts_ara.matrss.de >> ~/.ssh/known_hosts
      fi
  script:
    - nix flake check
    - nix build .#nixosConfigurations.andromeda.config.system.build.toplevel
    - nix build .#nixosConfigurations.ara.config.system.build.toplevel
    - |-
      if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
        nix store sign -k "$NIX_SIGNATURE_KEY" -r .#nixosConfigurations.andromeda.config.system.build.toplevel
        nix store sign -k "$NIX_SIGNATURE_KEY" -r .#nixosConfigurations.ara.config.system.build.toplevel
        nix copy --to ssh://nix-ssh@ara.matrss.de .#nixosConfigurations.andromeda.config.system.build.toplevel
        nix copy --to ssh://nix-ssh@ara.matrss.de .#nixosConfigurations.ara.config.system.build.toplevel
      fi
