###############################################################
#                   Authelia configuration                    #
###############################################################

theme: dark
server:
  host: 0.0.0.0
  port: 9091
log:
  level: info
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# jwt_secret:

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: traefik.ara.matrss.de
      policy: two_factor
      subject: "group:admins"

    - domain: whoami.ara.matrss.de
      policy: two_factor
      subject: "group:users"

    - domain: jellyfin.ara.matrss.de
      policy: bypass
      # policy: two_factor
      # subject: "group:users"

    - domain: nextcloud.ara.matrss.de
      policy: bypass

    - domain: vaultwarden.ara.matrss.de
      resources:
        - "^/api/.*$"
        - "^/identity/connect/token$"
      policy: bypass

    - domain: vaultwarden.ara.matrss.de
      policy: two_factor
      subject: "group:users"

    - domain: sonarr.ara.matrss.de
      policy: two_factor
      subject: "user:matrss"

    - domain: radarr.ara.matrss.de
      policy: two_factor
      subject: "user:matrss"

    - domain: bazarr.ara.matrss.de
      policy: two_factor
      subject: "user:matrss"

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret:
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: ara.matrss.de # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: matthias.risze@gmail.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password:
    host: smtp.gmail.com
    port: 587
    sender: admin@matrss.de
