name: Build flake outputs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - id: set-matrix
        name: Generate matrix
        run: |
          matrix=$(
            nix flake show --refresh --json "." |
              jq '{ attr: ((path(.. | select(.type? == "derivation")) | map((if (. | contains(".")) then "\"" + . + "\"" else . end)) | join(".")),
                           (path(.. | select(.type? == "nixos-configuration")) | map((if (. | contains(".")) then "\"" + . + "\"" else . end)) | join(".") | . + ".config.system.build.toplevel"))
                  }' |
              jq --slurp --compact-output
          )
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    needs: nix-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v13
        with:
          name: matrss
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L '.#${{ matrix.attr }}'
