name: Build flake outputs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - id: set-matrix
        name: Generate matrix
        run: |
          matrix=$(
            nix flake show --refresh --all-systems --json "." |
              jq '
                def system_to_os: {
                  "aarch64-linux": "ubuntu-latest",
                  "x86_64-darwin": "macos-latest",
                  "x86_64-linux": "ubuntu-latest",
                }[.] // empty;
                def quote: map((if (. | contains(".")) then "\"" + . + "\"" else . end));
                (path(.. | select(.type? == "derivation")) | quote | { attr: join("."), os: .[1] | system_to_os }),
                (path(.. | select(.type? == "nixos-configuration")) | quote | join(".") | . + ".config.system.build.toplevel" | { attr: . , os: "ubuntu-latest" })
              ' |
              jq --slurp --compact-output
          )
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            always-allow-substitutes = true
            ${{ startsWith(matrix.os, 'ubuntu') && 'extra-platforms = aarch64-linux' || ' ' }}
      - uses: cachix/cachix-action@v14
        with:
          name: matrss
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build output
        run: |
          drv=$(nix path-info --derivation '.#${{ matrix.attr }}')
          out=$(nix derivation show $drv^* | jq -r ".\"$drv\".outputs.out.path")
          hash=$(echo $out | cut -d/ -f4 | cut -d- -f1)
          is_cached() {
            curl --fail "https://matrss.cachix.org/$hash.narinfo" > /dev/null 2>&1
          }
          if is_cached $hash; then
            echo "output is cached, nothing to do"
            exit 0
          fi
          nix build -L $drv^*
