name: Deploy NixOS systems

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: live
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/deploy_key
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/deploy_key
          cp ssh_known_hosts ~/.ssh/known_hosts
      - name: Collect systems
        run: |
          systems=$(
            nix flake show --refresh --all-systems --json "." |
              jq '
                path(.. | select(.type? == "nixos-configuration")) | last
              ' |
              jq --slurp --compact-output
          )
          echo "systems=$systems" >> "$GITHUB_ENV"
      - name: Deploy systems
        run: |
          echo "$systems" | jq -r '.[]' | xargs -P2 -I{} bash -c '
            if host "{}"; then
              ssh -i ~/.ssh/deploy_key root@"{}" system-upgrade 2>&1 |
                tee {}-deploy.log |
                while read -r line; do printf '"'"'{}: %s\n'"'"' "$line"; done
            else
              echo "::notice::The system {} is not reachable, skipping its deployment"
            fi
          '
      - name: Show deploy logs
        if: ${{ !cancelled() }}
        run: |
          echo "$systems" | jq -r '.[]' | while read -r fqdn; do
            echo "::group::$fqdn"
            cat "$fqdn"-deploy.log || echo ""
            echo "::endgroup::"
          done
