[global]
sendAnonymousUsage = false


[log]
level = "warn"


[accessLog]
filePath = "/data/access.log"
bufferingSize = 100

[accessLog.filters]
statusCodes = "400-499"


[api]
dashboard = true


[entryPoints.web]
address = ":80"

[entryPoints.web.http.redirections.entrypoint]
to = "websecure"
scheme = "https"


[entryPoints.websecure]
address = ":443"

[entryPoints.websecure.http.tls]
certresolver = "letsencrypt"


[providers.file]
directory = "/etc/traefik/dynamic-config"


[providers.docker]
exposedByDefault = false
# defaultRule = "Host(`{{ trimPrefix `/` .Name }}.ara.matrss.de`)"


[certificatesResolvers.letsencrypt.acme]
email = "matthias.risze@gmail.com"
storage = "/data/letsencrypt-acme.json"
## Enable the let's encrypt staging servers for testing purposes
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[certificatesResolvers.letsencrypt.acme.httpChallenge]
# used during the challenge
entryPoint = "web"